### ISSUE TITLE
Is the snap config info from `get_version` the same as the info from `get_config`?

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_corr_cm#17]
Specifically, will I get the same sets of "config" , "config_timestamp" and  "config_md5"  from these two methods?

**Comment by bhazelton** [comment]
I know that `get_config` returns the configuration as a yaml processed string, is `get_version` returning the same thing in the snap config field or is it a filename? The code suggests the former, but the docstring suggests the latter to me.

**Comment by jack-h** [comment]
It appears to be storing an unprocessed yaml string. I'll update this so that they both return yaml-processed structures.
Note that the configuration information returned by `get_version` returns the configuration used on the last snap initialization. `get_config` returns the configuration currently stored in redis. By default the stored configuration is the one that gets used on initialization, but users can override this by supplying a local configuration file.

**Comment by jack-h** [comment]
As of d5355c1b, both functions return yaml-processed strings. `get_version` docstring updated.

**Comment by bhazelton** [comment]
Thank you! I understood the distinction between what's stored and what's initialized, but I'm tracking unique config files in the librarian, so I wanted to be sure that I could re-use the code I have to do that. This should make it all work properly.
