### ISSUE TITLE
expected keys from get_version

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_corr_cm#18]
The docstring of `get_version` says that the keys of the returned dict will be software packages, e.g. "hera_corr_f". I find that the keys are a bit more complicated and include the python filename being called:
```['udpSender:hera_node_keep_alive.py',
 'hera_corr_f:hera_snap_redis_monitor.py',
 'udpSender:hera_node_cmd_check.py',
 'snap',
 'udpSender:hera_node_receiver.py',
 'hera_corr_cm']
```
Note the 3 separate keys for `udpSender` -- they have the same version but different timestamps.

Is this the expected & desired behavior?

**Comment by jack-h** [comment]
Documentation fail. Keys can be of the form <package> or <package>:<script> for daemonized processes. For example, the udpSender package includes various daemons which in a sane world would all be running from the same installed version of the udpSender package. Since this isn't necessarily the case (it's easy to accidentally / deliberately reinstall udpSender, but only restart a subset of daemons) they all report their versions separately. The timestamps represent the time that the script / package version was reported -- for daemons, this is the time the daemon started running.

Updated docstring in b43b2b7209

**Comment by bhazelton** [comment]
Thank you, that's very helpful. 

My plan is to have a new row in M&C for each unique time and package, so that we capture all this info. My big question is about hera_corr_cm. I see that it will have a unique time every time the `get_version` method is called, which could generate a lot of rows in this table. Do you think I should check what the prior version is and not write a new row if it's the same? Or should I write a new row at least every so often (day?) as well as when it changes? Or just live with a lot of hera_corr_cm rows?

**Comment by jack-h** [comment]
I think only writing on a version change, or when your monitoring daemon
script starts is probably what i'd do. Since it's installed locally, you
could also just use whatever infrastructure you already have to track
python packages and ignore the value returned by the hera_corr_cm
get_version call altogether.

**Comment by bhazelton** [comment]
Thanks!
